### PR TITLE
Sets opponent's face as current mouse position

### PR DESCRIPTION
**Pull request by AiSatan**
I hooked one more method and now I can work in same time while the bot working.
Bot always aiming to the opponent's hero face (if bot is enabled) even if mouse out of the game screen.

I also changed "ilp.Body.Variables.Add(new VariableDefinition" because it's not work with return type like Vector3 in my case, maybe I did something wrong, but works fine.

### CODE REVIEW

**Comment by yangyuan** [comment]
Thanks for this pull request.

I know the method UniversalInputManager.GetMousePosition before, but hooking that will disable all other game mouse features and mess up PlayZoneSlotMousedOver so I didn't hook that.
But since we have already hooked PlayZoneSlotMousedOver, maybe its okay to do hook GetMousePosition.

There are a couple of issues (StyleCop issue and class designing issue) in the code. I don't want to waste your time so I merge this PR to a develop branch and will merge to master after fixed the issues.

Thanks again for the contribution.

**Comment by yangyuan** [comment]
And also the "opponent face position" will trigger some network message (the abnormal might be detected  by server). So I moved the hook location to the center of the stage (8/15 of the screen).

**Comment by AiSatan** [comment]
yes, thank you too.

I trying use StyleCop with resharper, just I don't use it before, a little hard for me

> And also the "opponent face position" will trigger some network message
I think, we can return card.transform.position > convert it to screenView with Camera object, and set it as mouse position. And the cursor always be over a target, how do you think?

**Comment by yangyuan** [comment]
I haven't tried but `Component.transform.position` doesn't seem to be a good choice.
- It requires a card, which card to use? There some states (like 'searching games') when there is no card.
- As a hook feature, I prefer to keep it simple.

**Comment by AiSatan** [comment]
> It requires a card, which card to use?

I tried use it (and  it did not help) with battlecry's issue
I used the same card, that came to Click method, and it did work just fine
I told you about this just for thinking
> (the abnormal might be detected by server)

and, 

> As a hook feature, I prefer to keep it simple.

yes, good choice :)

**Pull request merged**
